---
- name: Setup Self Hosted Database Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: self_hosted_private_network
    - role: mariadb
    - role: mysqld_exporter
    - role: deadlock_logger
