---
- name: Regenerate Wireguard Config
  template:
    src: wg.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600

- name: Stop WireGuard
  systemd:
    name: wg-quick@wg0
    state: stopped
    enabled: true

- name: Start WireGuard
  systemd:
    name: wg-quick@wg0
    state: started
    enabled: true
